1.	Dla zmiennych losowych przedstawionych w tabeli obliczyć podstawowe statystyki

Wartość 1 2 3 4 5 6
Prawdopodobieństwo 1/6 1/6 1/6 1/6 1/6 1/6

In [7]:
import pandas as pd

wartosc = [1,2,3,4,5,6]
prawdopodobienstwo = [1/6 for x in range(6)]

In [8]:
prawdopodobienstwo

[0.16666666666666666,
 0.16666666666666666,
 0.16666666666666666,
 0.16666666666666666,
 0.16666666666666666,
 0.16666666666666666]

In [9]:
prawdopodobienstwo = pd.DataFrame(prawdopodobienstwo)

In [10]:
prawdopodobienstwo

0
0  0.166667
1  0.166667
2  0.166667
3  0.166667
4  0.166667
5  0.166667

In [11]:
prawdopodobienstwo.mean()

0    0.166667
dtype: float64

In [12]:
prawdopodobienstwo.var()

0    0.0
dtype: float64

In [13]:
prawdopodobienstwo.std()

0    0.0
dtype: float64

Wygeneruj próby dla n=100 dla następujących rozkładów: Bernoulliego, Dwumianowego, Poissona

In [31]:
from scipy.stats import bernoulli, binom, poisson

In [20]:
Bern = bernoulli.rvs(0.4, size=100)
Bern

array([1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0])

In [25]:
r = binom.rvs(2, 0.5, size=100)

In [26]:
r

array([1, 1, 1, 1, 0, 2, 1, 1, 0, 1, 2, 2, 0, 1, 2, 1, 2, 1, 2, 1, 1, 2,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 2, 1, 1, 2, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 2, 1, 1, 1, 2, 2, 2, 2, 1, 0, 1, 1, 1, 0, 0, 1, 1, 2,
       1, 0, 1, 2, 0, 0, 1, 1, 0, 1, 1, 1, 1, 2, 0, 2, 1, 1, 1, 1, 1, 0,
       2, 1, 1, 2, 2, 0, 1, 2, 1, 2, 1, 2])

In [28]:
import numpy as np

In [37]:
mu = 0.5

In [42]:
poin = np.linspace(poisson.ppf(0.01, mu),
                poisson.ppf(0.90, mu))

In [43]:
poin

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])